### ISSUE TITLE
Wiki - Infoboxy

### ISSUE THREAD

**Issue by Gwyndrichstein** [Gwyndrichstein/Silverhold#3]
Sem psát žádané úpravy infoboxů. Postupně budu odbavovat.

**Comment by Orikulus** [comment]
Bylo by fajn přidat do infoboxu lokace možnost přidávat co v dané lokaci žije za rasy. (Chceme rvát všudy ty sexy ikonky)

**Comment by Antti0** [comment]
Do infoboxu frakce přidat možnost pro sekundární vůdce (zástupce) a status (jako aktivní, zaniklá...).

**Comment by Gwyndrichstein** [comment]
Dodáno.
